use sdkwork_web_core::{HttpRouteManifest, HttpRoute, HttpMethod};

use crate::paths::SDK_DOMAIN;

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/notifications",
        SDK_DOMAIN,
        "messaging.notifications.list",
    )
    .with_required_permission("messaging.notifications.get"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/messaging/notifications",
        SDK_DOMAIN,
        "messaging.notifications.create",
    )
    .with_required_permission("messaging.notifications.post")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/announcements",
        SDK_DOMAIN,
        "messaging.announcements.list",
    )
    .with_required_permission("messaging.announcements.get"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/messaging/announcements",
        SDK_DOMAIN,
        "messaging.announcements.publish",
    )
    .with_required_permission("messaging.announcements.post")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/push_messages",
        SDK_DOMAIN,
        "messaging.pushMessages.list",
    )
    .with_required_permission("messaging.pushMessages.get"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/messaging/push_messages",
        SDK_DOMAIN,
        "messaging.pushMessages.send",
    )
    .with_required_permission("messaging.pushMessages.post")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/outbound_messages",
        SDK_DOMAIN,
        "messaging.outboundMessages.list",
    )
    .with_required_permission("messaging.outboundMessages.get"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/messaging/outbound_messages",
        SDK_DOMAIN,
        "messaging.outboundMessages.send",
    )
    .with_required_permission("messaging.outboundMessages.post")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/verification_policies",
        SDK_DOMAIN,
        "messaging.verificationPolicies.list",
    )
    .with_required_permission("messaging.verificationPolicies.get"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/messaging/verification_policies/{policyId}",
        SDK_DOMAIN,
        "messaging.verificationPolicies.update",
    )
    .with_required_permission("messaging.verificationPolicies.put")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/channels/{channel}",
        SDK_DOMAIN,
        "messaging.channels.retrieve",
    )
    .with_required_permission("messaging.channels.get"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/messaging/channels/{channel}",
        SDK_DOMAIN,
        "messaging.channels.update",
    )
    .with_required_permission("messaging.channels.put")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/templates",
        SDK_DOMAIN,
        "messaging.templates.list",
    )
    .with_required_permission("messaging.templates.get"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/messaging/templates",
        SDK_DOMAIN,
        "messaging.templates.create",
    )
    .with_required_permission("messaging.templates.post")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/messaging/templates/{templateId}",
        SDK_DOMAIN,
        "messaging.templates.retrieve",
    )
    .with_required_permission("messaging.templates.get"),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/messaging/templates/{templateId}",
        SDK_DOMAIN,
        "messaging.templates.update",
    )
    .with_required_permission("messaging.templates.put")
    .with_idempotent(true),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/messaging/templates/{templateId}",
        SDK_DOMAIN,
        "messaging.templates.delete",
    )
    .with_required_permission("messaging.templates.delete")
    .with_idempotent(true),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}

pub fn route_definitions() -> &'static [HttpRoute] {
    HTTP_ROUTES
}
